import { ScheduledPost } from '../types';

export const INITIAL_SCHEDULED_POSTS: ScheduledPost[] = [
  {
    id: 'post-101',
    repoName: 'vijaymahes9080/RepoVision-AI',
    postTitle: '🚀 Introducing RepoVision AI – Automate GitHub to LinkedIn Publishing',
    postBody: 'Excited to launch RepoVision AI! Automate your open source marketing with AI...',
    hashtags: ['#AI', '#OpenSource', '#React', '#GitHub'],
    scheduledDate: '2026-08-06',
    scheduledTime: '09:30 AM',
    status: 'scheduled',
    mediaType: 'carousel',
    linkedInAccount: 'Vijay Mahes (Personal Profile)',
    engagementScoreEstimate: 94,
  },
  {
    id: 'post-102',
    repoName: 'fastapi/fastapi',
    postTitle: '⚡ High Performance Async APIs with FastAPI & Python',
    postBody: 'Deep dive into why FastAPI is the #1 framework for high-throughput AI backends...',
    hashtags: ['#Python', '#FastAPI', '#Backend', '#APIs'],
    scheduledDate: '2026-08-07',
    scheduledTime: '02:00 PM',
    status: 'scheduled',
    mediaType: 'banner',
    linkedInAccount: 'Vijay Mahes (Personal Profile)',
    engagementScoreEstimate: 88,
  },
  {
    id: 'post-103',
    repoName: 'langchain-ai/langchain',
    postTitle: '🧠 Building Agentic RAG Pipelines with LangChain & Vector DBs',
    postBody: 'Learn how to compose memory, vector stores, and custom tools in LangChain...',
    hashtags: ['#AI', '#LangChain', '#LLMs', '#RAG'],
    scheduledDate: '2026-08-03',
    scheduledTime: '10:00 AM',
    status: 'published',
    mediaType: 'carousel',
    linkedInAccount: 'Vijay Mahes (Personal Profile)',
    engagementScoreEstimate: 96,
  },
  {
    id: 'post-104',
    repoName: 'vercel/next.js',
    postTitle: '🌐 The Future of Web Architecture: Next.js App Router',
    postBody: 'Server Components and Streaming SSR explained simply...',
    hashtags: ['#NextJS', '#React', '#WebDev'],
    scheduledDate: '2026-08-02',
    scheduledTime: '04:15 PM',
    status: 'published',
    mediaType: 'banner',
    linkedInAccount: 'Vijay Mahes (Personal Profile)',
    engagementScoreEstimate: 91,
  },
];
